version: '3'
services:
  app:
    build: .
    ports:
      - "8090:8080"
  mariadb:
    image: "mariadb:latest"
    ports:
      - "3306:3306"
    volumes:
      - /root/docker/mariadb/datadir:/var/lib/mysql