version: '3'
services:
  mariadb:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "devopsmaonamassa"
      MYSQL_DATABASE: "notes"
    ports:
      - "3306:3306"
    volumes:
      - /root/docker/mariadb/datadir:/var/lib/mysql
  app:
    build: .
    ports:
      - "8090:8080"